#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only

START=95
USE_PROCD=1

start_service() {
	[ "$(uci -q get ucrashreport.settings.enabled)" = 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/ucrashreportd
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger ucrashreport
}
